Adição da página de configurações de usuário
Turina7/ByeByeDengue pull request #30
Opened 2024-11-19 14:48 UTC by giovani-seb

2024-11-19 17:16 UTC, marinhotg requested changes
as funções com o backend estão ótimas.

falta só arrumar oq comentei acima

2024-11-19 17:16 UTC, marinhotg commented on app/(pages)/settings/page.tsx
> +      console.error("Usuário não autenticado");
não eh bom fazer assim. as vzs o usuario ta conectado, mas nao deu tempo suficiente para essa info chegar.

aqui ao inves de mudar a rota, dê um return <Loading />, para carregar enquanto nao estiver com o usuario populado.

2024-11-19 17:16 UTC, marinhotg commented on app/components/tabMenu/tabMenu.tsx
> +  const [isDropDownOpen, setIsDropDownOpen] = useState(false);
tem que melhorar a responsividade. o dropdown continua aberto quando clico nele

2024-11-19 17:16 UTC, marinhotg commented on app/components/tabMenu/tabMenu.tsx
> +                <Image src={gearIcon} alt="Gear Icon" width={16} height={16} className={styles.icon} />
veja se tem uma forma do gear icon ficar mais proximo do botão

2024-11-19 19:12 UTC, giovani-seb commented on app/(pages)/settings/page.tsx
> +      console.error("Usuário não autenticado");
Fui mais pelo que tava nas outras páginas, mas não entendi o "return Loading"

2024-11-19 19:13 UTC, giovani-seb commented on app/components/tabMenu/tabMenu.tsx
> +                <Image src={gearIcon} alt="Gear Icon" width={16} height={16} className={styles.icon} />
Você diz mais próximo do ícone de usuário ou do botão Entrar/Sair?

2024-11-28 14:04 UTC, marinhotg approved these changes
ficou mt brabo nice

2024-11-28 14:25 UTC, merged